DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, NUMEROMATRICULA INT NOT NULL);

INSERT INTO ODONTOLOGOS ( NOMBRE, APELLIDO, NUMEROMATRICULA) VALUES ('CARLOS', 'JIMENEZ', 1234);
INSERT INTO ODONTOLOGOS ( NOMBRE, APELLIDO, NUMEROMATRICULA) VALUES ('LUCIANA', 'MURGA', 3210);
INSERT INTO ODONTOLOGOS ( NOMBRE, APELLIDO, NUMEROMATRICULA) VALUES ('VICTOR', 'CALABRO', 4567);
INSERT INTO ODONTOLOGOS ( NOMBRE, APELLIDO, NUMEROMATRICULA) VALUES ('SERGIO', 'REGALADO', 8910);


